language: go

go:
  - 1.6
  - tip

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/modocache/gover

script:
  - go test -v -coverprofile=middleware.out ./middleware
  - go test -v -coverprofile=middleware.out ./models
  - go test -v -coverprofile=middleware.out ./utils

after_success:
  - gover
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken CnkKv2SjzfuLm8gTvLRpB5DuIlotSx7mj
